# Generated by Django 2.2.5 on 2020-01-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0002_auto_20200105_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mobile_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
