# Generated by Django 2.2.5 on 2020-01-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0003_auto_20200105_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=120)),
                ('item_name', models.CharField(max_length=120)),
                ('specification', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('email_id', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('model_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='max.Electronics')),
            ],
        ),
    ]
