# Generated by Django 2.2.5 on 2020-01-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0004_electronics_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='item_id',
        ),
    ]
