# Generated by Django 2.2.5 on 2020-01-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0005_remove_electronics_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
