# Generated by Django 2.2.5 on 2020-01-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0009_electronics_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='select',
            field=models.CharField(max_length=120),
        ),
    ]
