# Generated by Django 2.2.5 on 2020-01-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0011_auto_20200107_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='select',
        ),
        migrations.AddField(
            model_name='electronics',
            name='item_id',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
