# Generated by Django 2.2.5 on 2020-01-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0015_auto_20200108_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='name_type',
        ),
    ]
