# Generated by Django 2.2.5 on 2020-01-08 05:58

from django.db import migrations, models
import django.db.models.deletion
import max.models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0019_auto_20200108_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='name_type',
            field=models.ForeignKey(default=max.models.Name, on_delete=django.db.models.deletion.CASCADE, to='max.Name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='model_seller',
            field=models.ForeignKey(default=max.models.Electronics, on_delete=django.db.models.deletion.CASCADE, to='max.Electronics'),
        ),
    ]
