# Generated by Django 2.2.5 on 2020-01-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0020_auto_20200108_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='srno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
