# Generated by Django 3.0.2 on 2020-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0022_remove_electronics_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='specification',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
